### ISSUE TITLE
how to install it  ???

### ISSUE THREAD

**Issue by kjji01** [Agantor/viewerbot#12]
https://prnt.sc/rvml0n always have this error

**Comment by linux21123** [comment]
This error comes everytime when you don't use Python3.7 install that on your system and install all than with pip3.7 install -r requirements.txt and than you can use it with python3.7 thread_viewer
because python3 can't use that line f("Send    that f <---- is the Problem because that you must use Python3.7

**Comment by Retch** [comment]
> This error comes everytime when you don't use Python3.7 install that on your system and install all than with pip3.7 install -r requirements.txt and than you can use it with python3.7 thread_viewer
> because python3 can't use that line f("Send that f <---- is the Problem because that you must use Python3.7

How should this work?

~/viewerbot$ pip3.7 install -r requirements.txt
            -bash: pip3.7: command not found
