### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by massivly** [Agantor/viewerbot#2]
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    channel_url = "https://www.twitch.tv/" + sys.argv[1]
IndexError: list index out of range

**Comment by Agantor** [comment]
Hello there, you have to specify the channel you want to use. It should be something like this:

`~\viewerbot>python threads_viewer.py RANDOMCHANNEL 1000` where RANDOMCHANNEL is the name of your channel. 

If not, you are free to edit script so that "channel_url" corresponds to URL of your channel. Something like " https://www.twitch.tv/RANDOMCHANNEL" 

you have to change `channel_url = "https://www.twitch.tv/" + sys.argv[1]` by `channel_url = "https://www.twitch.tv/RANDOMCHANNEL"` where, again, RANDOMCHANNEL is the name of your channel.
